import {
  AlertTriangle,
  ArrowRight,
  ChevronLeft,
  ChevronRight,
  Command,
  CreditCard,
  File,
  FileText,
  HelpCircle,
  Image,
  Laptop,
  Loader2,
  Moon,
  MoreVertical,
  Pizza,
  Plus,
  Settings,
  SunMedium,
  Trash,
  User,
  X,
  BotIcon,
  FolderClosed,
  LayoutDashboard,
  Key,
  Coins,
  ArrowUp,
  CheckCheck,
  ArrowDown,
  Import,
  BadgePlus,
  Copy,
  Download,
  Send,
  Loader,
  RefreshCcw,
  Paperclip,
  Lock,
} from 'lucide-react';

export const Icons: any = {
  lock: Lock,
  document: File,
  paperclip: Paperclip,
  reload: RefreshCcw,
  loading: Loader,
  send: Send,
  download: Download,
  copy: Copy,
  badgeplus: BadgePlus,
  import: Import,
  logo: Command,
  folder: FolderClosed,
  dashboard: LayoutDashboard,
  close: X,
  key: Key,
  checkcheck: CheckCheck,
  coin: Coins,
  spinner: Loader2,
  chevronLeft: ChevronLeft,
  chevronRight: ChevronRight,
  trash: Trash,
  post: FileText,
  page: File,
  media: Image,
  settings: Settings,
  billing: CreditCard,
  ellipsis: MoreVertical,
  add: Plus,
  bot: BotIcon,
  warning: AlertTriangle,
  user: User,
  arrowRight: ArrowRight,
  arrowUp: ArrowUp,
  arrowDown: ArrowDown,
  help: HelpCircle,
  pizza: Pizza,
  sun: SunMedium,
  moon: Moon,
  laptop: Laptop,
};
